name: Test Build Workflows

on:
  push:
    branches:
      - '*'
      - '!main'
      - '!generated/*'

env:
  BUILD_DIR: generated

jobs:
  generate-workflows:
    runs-on: arc-systems
    steps:
      - uses: actions/checkout@v3
      - name: Generate workflows
        uses: unknorg/workflow-preprocessor@1.0.3
        with:
          generated-directory: ${{ env.BUILD_DIR }}
      - name: Rename generated workflows
        run: find ${{ env.BUILD_DIR }} -type f -name '*.yml' -exec bash -c 'mv "$1" "${1%.yml}.gen.yml"' _ {} \;
      - uses: actions/upload-artifact@v3
        with:
          name: generated-workflows
          path: ${{ env.BUILD_DIR }}
          retention-days: 1
  generated-branch:
    name: Create or update generated branch
    runs-on: arc-systems
    needs: [generate-workflows]
    env:
      GENERATED_BRANCH: generated/${{ github.ref_name }}
    outputs:
      GENERATED_CHANGED: ${{ steps.configure.outputs.GENERATED_CHANGED }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPOSITORY_TOKEN }}
          fetch-depth: 0
          ref: ${{ github.ref_name }}
      - name: Checkout to branch
        run: |    # TODO: do we even need to delete the branch (since we checkout elsewhere)
          if git show-ref --verify --quiet "refs/heads/${{ env.GENERATED_BRANCH }}"; then
            echo 'Deleting existing local branch';
            git branch -D '${{ env.GENERATED_BRANCH }}';
          fi
          git checkout -b '${{ env.GENERATED_BRANCH }}'
      - name: Remove possibly existing generated workflows
        run: find .github/workflows -type f -name '*.gen.yml' -exec bash -c 'rm -f "$1"' _ {} \;
      - uses: actions/download-artifact@v3
        with:
          name: generated-workflows
          path: .github/workflows
      - name: Configure git and check for changes
        id: configure
        run: |
          git add .github/workflows/*
          changed=$(git status -s | grep -E "[RAM]\s+.github/workflows" | wc -l);
          echo "GENERATED_CHANGED=$changed" >> $GITHUB_ENV
          echo "GENERATED_CHANGED=$changed" >> $GITHUB_OUTPUT
      - name: Push changes to branch
        if: ${{ env.GENERATED_CHANGED >= '1' }}
        run: |
          git config user.email whitesmith.thedj@gmail.com
          git config user.name 'Hathoute (auto)'
          git commit -m 'chore: add built workflow'
          git push -f --set-upstream origin '${{ env.GENERATED_BRANCH }}'

  generated-pr:
    name: Create pull request if not exists
    runs-on: arc-systems
    needs: [generated-branch]
    permissions:
      pull-requests: write
    env:
      GENERATED_BRANCH: generated/${{ github.ref_name }}
    if: ${{ needs.generated-branch.outputs.GENERATED_CHANGED >= '1' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.GENERATED_BRANCH }}
      - run: |
          echo "::debug::Creating new PR: "
          echo "::debug::   - repository: $REPO_NAME"
          echo "::debug::   - branch:     $BRANCH_NAME"
          echo "::debug::   - assignee:   $BRANCH_OWNER"
          if MESSAGE=$( gh pr create --repo "$REPO_NAME" --assignee "$BRANCH_OWNER" --head "$BRANCH_NAME" --draft --title "$PR_TITLE" --body "Auto PR" 2>&1 >/dev/null ) || echo "$MESSAGE" | grep -q "a pull request for branch .* into branch .* already exists"
          then
            echo "::debug::Pull request already exists"
            exit 0
          elif echo "$MESSAGE" | grep -q "Draft pull requests are not supported"
          then
            echo "::debug::Repository does not support draft pull requests"
            gh pr create --repo "$REPO_NAME" --assignee "$BRANCH_OWNER" --head "$BRANCH_NAME" --title "$PR_TITLE" --body "Auto PR"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ env.GENERATED_BRANCH }}
          BRANCH_OWNER: ${{ github.actor }}
          REPO_NAME: ${{ github.repository }}
          PR_TITLE: Generated workflows for ${{ github.ref_name }}